### ISSUE TITLE
Latest version breaks click events for some chart types.

### ISSUE THREAD

**Issue by jarrettj** [blacklabel/custom_events#90]
Hi,

I'm using custom_events v1.1.3 with highcharts v5.0.9 and it works.

Tried upgrading to custom_events v2.0.10.

The click events no longer has the point passed through as this. If I do a console.log I get the Window object instead. This is only true for the bubble and mapbubble chart types. The pie and bar click events work as before.

JJ

**Comment by sebastianbochan** [comment]
Thank you for the reporting, I will fix it as soon as possible.

**Comment by sebastianbochan** [comment]
Currently Im developing new version and fixed #89, #91 bugs. Could you prepare simple demo of your unworking scenario (jsfiddle)? It will allow me to test your case too and prepare final release.

**Comment by jarrettj** [comment]
Thanks man. I'll get it to you in the moro. Public holiday today. :)

**Comment by sebastianbochan** [comment]
I committed the upgrade, please test in your scenari and if problem will appear, supply it as live demo.

**Comment by italomaia** [comment]
I'm also affected by this issue. Using version 2.0.11 and t he problem is still there.

**Comment by jarrettj** [comment]
Doesn't work here either. Let me get a jsfiddle going.

**Comment by italomaia** [comment]
This seems to be the cause: 

`elemObj = eventObject.searchPoint(normalizedEvent, eventObject.kdDimensions === 1); // #87 - wrong searchPoint for scatter series`

Line 253

**Comment by italomaia** [comment]
@jarrettj @sebastianbochan If I comment line 253 with the so said line, the problem seems to be solved; I'm using a piechart here. 

What does this line actually do? I'm not familiar with the "searchPoint for scatter series" concept.

**Comment by jarrettj** [comment]
It's not a piechart issue though. Bubble and mapbubble affected though.

**Comment by italomaia** [comment]
Would you mind giving https://github.com/blacklabel/custom_events/pull/92 a try, @jarrettj

**Comment by jarrettj** [comment]
Hi @sebastianbochan .

Sorry for the delay! Here you go. 

Working: https://jsfiddle.net/jjordaan/uu3b0wtz/
Broken: https://jsfiddle.net/jjordaan/uu3b0wtz/1/

The working version uses Custom events v1.1.3. The broken one uses the latest commit.

Thanks for the help man. Much appreciated

Regards.
JJ

**Comment by sebastianbochan** [comment]
Thank you for demos. The issue was in pie chart, boxplot and bubble chart. Now all references are proper, if not, please reopen the ticket.

**Comment by jarrettj** [comment]
Hey, fixed!

Thanks @sebastianbochan! All works now again. Sorry for the hassle, I just like to keep packages up-to-date. :)

Regards.
JJ

**Comment by sebastianbochan** [comment]
@jarrettj Sounds great, thanks for the feedback.

**Comment by hopest** [comment]
@sebastianbochan The event does not work if you update the series type, for example

**Comment by sebastianbochan** [comment]
Thank you for the feedback. I opened new ticket with this bug here: #93
